src/objects/GlobalSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/ServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Strategy__c</fullName>
        <description>Allowed Values:
1. SOAPService
2. RESTService</description>
        <inlineHelpText>Allowed Values:
1. SOAPService
2. RESTService</inlineHelpText>
        <label>Strategy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Settings</label>
</CustomObject>

src/classes/Service.cls
public without sharing class Service{
   
    private ServiceSettings__c serviceSettings;
    public class StrategyNameException extends Exception{}
    public class ServiceSettingException extends Exception{}
    private ServiceInterface strategy;
    public static final Map<String, ServiceInterface> strategies;
    
    static{
        GlobalSettings__c serviceStrategies = GlobalSettings__c.getInstance(ServiceHelper.serviceStrategies);
        List<String> strategyNames = new List<String>();
        
        if(serviceStrategies != null && serviceStrategies.value__c != null)
            strategyNames = serviceStrategies.value__c.split(',');
            
        strategies = new Map<String, ServiceInterface>();
        
        for(String name : strategyNames){
            try{
                strategies.put(name, (ServiceInterface)Type.forName(name).newInstance());                    
            }
            catch(Exception e){
              system.debug('Strategy Exception : ' + e.getMessage());
                continue;
            }
        }    
    }   
    
    public Service(String serviceName){
        serviceSettings = ServiceSettings__c.getInstance(serviceName);
        if(serviceSettings != null){
          if(!strategies.containsKey(serviceSettings.Strategy__c))
              throw new StrategyNameException(serviceSettings.Strategy__c);
          strategy = strategies.get(serviceSettings.Strategy__c);
        }
        else
          throw new ServiceSettingException('Error : Service Configuration Setup is Missing for : ' + serviceName);
    }    
    
    public Object callout(Object serviceInput){        
        return strategy.performServiceCallout(serviceSettings, serviceInput);
    }
    
}