src/objects/ServiceSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Certificate__c</fullName>
        <label>Certificate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>HeaderName__c</fullName>
        <description>Select the Header name from ServiceHeaders settings</description>
        <inlineHelpText>Select the Header name from ServiceHeaders settings</inlineHelpText>
        <label>Header Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Log Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProcessingClass__c</fullName>
        <label>ProcessingClass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Settings</label>
</CustomObject>

src/objects/StatusLog__c.object
<CustomObject>
    <fields>
        <fullName>CalloutTime__c</fullName>
        <label>CalloutTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ErrorCode__c</fullName>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <label>Error Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InputProcessingTime__c</fullName>
        <label>Input Processing Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OutputProcessingTime__c</fullName>
        <label>Output Processing Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestBody__c</fullName>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResponseBody__c</fullName>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <label>UID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Status Log</label>
    <nameField>
        <label>StatusLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BASEService.cls
public without sharing abstract class BASEService implements ServiceInterface {
  
  public ServiceSettings__c serviceSettings; 
  public string guid;
  
  public string serviceEndpoint;
  public map<string, string> requestHeader;
  public string certificate;
  public Object requestBody;
  
  public Map<string, string> responseHeader;
  public Object responseBody;
  
  public ServiceStatus serviceStatus = new ServiceStatus();
  
  private Object serviceOutput;
  public ServiceIO serviceIO;
  
  private long serviceInputProcessingTime;
  private long serviceCalloutTime;
  private long serviceOutputProcessingTime;
    
  private abstract void prepareServiceRequest();
   
    private abstract void execute();
    
    private abstract void processServiceResponse();
    
    private void getServiceEndPoint(){
      serviceEndpoint = serviceSettings.EndPoint__c;          
    }
    
    private void getRequestHeader(){
      requestHeader = ServiceHelper.getServiceHeaders(serviceSettings.HeaderName__c);    
    }
    
    private void getCertificate(){
      certificate = ServiceHelper.getCertificate(serviceSettings.Certificate__c);    
    }
    
    private void getRequestBody(Object serviceInput){
      if(serviceIO != null){        
          requestBody = serviceIO.convertInputToRequest(serviceInput, serviceEndpoint, requestHeader, guid);          
          System.debug('Service Input : ' + serviceInput);
          System.debug('Service Endpoint : ' + serviceEndpoint);
          System.debug('Service Request Header : ' + requestHeader);
      }
    }
    
    private void prepareOutput(){
      if(serviceIO != null){
        serviceOutput = serviceIO.convertResponseToOutput(responseBody, responseHeader, serviceStatus);
          System.Debug('Service Output : ' + serviceOutput);   
      }     
    }
    
    private void logServiceStatus(){
      if(serviceSettings.LogStatus__c){
          StatusLog__c statusLog = new StatusLog__c();
      statusLog.Name = serviceSettings.Name;
      statusLog.UID__c = guid;
          statusLog.Status__c = serviceStatus.status;          
          statusLog.ErrorCode__c = serviceStatus.errorCode;
          statusLog.ErrorDescription__c = serviceStatus.errorDescription;
          statusLog.InputProcessingTime__c = serviceInputProcessingTime;
          statusLog.CalloutTime__c = serviceCalloutTime;
          statusLog.OutputProcessingTime__c = serviceOutputProcessingTime;  
          if(requestBody != null){
            if(requestBody instanceof string)
              statusLog.RequestBody__c = (String) requestBody;
            else
              statusLog.RequestBody__c = string.valueof(requestBody);
          }
          if(responseBody != null){
            if(responseBody instanceof string)
              statusLog.ResponseBody__c = (String) responseBody;
            else
              statusLog.ResponseBody__c = string.valueof(responseBody);
          }
          
          StatusLogHelper.logStatus(statusLog, false);
          //Service service = new Service(ServiceHelper.serviceStatusLogService);        
          //Object status = service.callout(statusLog);      
                  
      }
    }
  
  public Object performServiceCallout(ServiceSettings__c serviceSettings, Object serviceInput){
    DateTime startTime = system.now();
    try{
      this.serviceSettings = serviceSettings;
      if(serviceSettings.ProcessingClass__c != null)
        this.serviceIO = new ServiceIO(serviceSettings.ProcessingClass__c);
      this.serviceStatus.status = 'S';
      this.guid = GUIDGenerator.generateGUID();
      system.debug('GUID : ' + guid);
          
      getServiceEndPoint();
      getRequestHeader();    
      getCertificate();
      getRequestBody(serviceInput);
          
      prepareServiceRequest();
    }
    catch(Exception ex){
      serviceStatus.status = 'E';
        serviceStatus.errorCode = 'Input';
        serviceStatus.errorDescription = ' Processing Error : ' + ex.getMessage();      
    }
    serviceInputProcessingTime = system.now().getTime() - startTime.getTime();
    
    startTime = system.now();
        try{                
            if(serviceStatus.status == 'S') execute();              
        } catch(Exception ex) {
            serviceStatus.status = 'I';
        serviceStatus.errorCode = 'Interface';
        serviceStatus.errorDescription = ex.getMessage();
        }  
        serviceCalloutTime = system.now().getTime() - startTime.getTime();
        
        startTime = system.now(); 
        try{  
          processServiceResponse();        
          prepareOutput();
        }
        catch(Exception ex){
          serviceStatus.status = 'E';
        serviceStatus.errorCode = 'Output';
        serviceStatus.errorDescription = ' Processing Error : ' + ex.getMessage();
        }
        serviceOutputProcessingTime = system.now().getTime() - startTime.getTime();
        
        logServiceStatus();
        
        return serviceOutput;
    }

}